fail_fast: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  # - id: check-yaml
#  - id: end-of-file-fixer
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
  - id: helmlint
- repo: https://github.com/kapilgarg1996/harness-helm-charts
  rev: main
  hooks:
  - id: generate-images-list
    args:
      - src/harness/images.txt
      - src/harness/images.txt
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.11.0
  hooks:
  - id: helm-docs